### ISSUE TITLE
I don't think my json is being parsed correctly?

### ISSUE THREAD

**Issue by SmItH197** [neilmcguiggan/JSONDemoApp#1]
When I run the following from my fragment:

``` JAVA
Log.d(TAG, "received parsed stockList: " + stockList);
```

I get:
`received parsed stockList: [in.bensmith.test.Stock@3e62bb90]`

I am trying to parse [this](http://www.google.com/finance/info?q=NASDAQ:GOOGL), I thought the double slash at the beginning might be causing problems so I used the following to remove them:

``` JAVA
String responseStringOld = response.body().string();
String responseString = responseStringOld.substring(4); 
```

Could this be messing it up?

**Comment by neilgmacy** [comment]
Hey Ben.

This isn't a JSON parsing issue. It looks like your `stockList` is an object of type `Stock`, is that right?

If you want to log `stockList` with some more detail, you should override the `toString()` method in the `Stock` class. By default that just includes the object type and hashcode, which is what you're seeing.

**Comment by SmItH197** [comment]
Sorry fairly new to Java,
how would I go about using the parsed data?
for example how would I log user.email for example? I can access it from inside UserDataParser.java but how would I access it elsewhere?
